language: java
jdk:
  - openjdk7
notifications:
  irc:
    channels:
      - "irc.esper.net#aero"
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
