language: java
jdk:
  - openjdk7
notifications:
  irc:
    channels:
      - "irc.esper.net#aero"
    template:
      - "Build #%{build_number} (https://github.com/%{repository}/commit/%{commit} : %{author}): %{message}"
