# This is the default config for BlockEnchant v2.0.3
# For further instructions on how to use this config, please visit the BukkitDev page below.
# http://dev.bukkit.org/server-mods/block-enchant/
#
Level: 15