# This is the default config for BlockEnchant v2.0.1
# For further instructions on how to use this config, please visit the BukkitDev page below.
# http://dev.bukkit.org/server-mods/blockenchant/
#
Level: 15