name: BlockEnchant
version: 2.0.3
author: iEpix
main: me.iaero.blockenchant.BlockEnchant
commands:
  blockenchant:
    aliases: [be, blockenchanthelp]
    description: Main help command for BlockEnchant