author: iAero
description: A plugin to block enchanting past a certain level to those without permission.
main: me.iaero.blockenchant.BlockEnchant
name: BlockEnchant
version: '2.2.1'
commands: 
  blockenchant:
    aliases: [be]
    description: Main command for BlockEnchant.
